default_choice: regular
settings:
 environment:
  framerate: 10
  framerate_limit: 0.075
  eo_archive_limit: 500000
  eo_archive_cleanup: 100000
  huge:
   w: 1000
   h: 750
  large:
   w: 800
   h: 600
  regular:
   w: 640
   h: 480
  small:
   w: 400
   h: 300
  profile:
   w: 640
   h: 480
 pond:
  huge:
   food_start: 367
   food_rate: 50
   eo_start: 24
   repop: 12
  large:
   food_start: 234
   food_rate: 35
   eo_start: 16
   repop: 10
  regular:
   food_start: 125
   food_rate: 25
   eo_start: 10
   repop: 5
  small:
   food_start: 50
   food_rate: 45
   eo_start: 4
   repop: 2
  profile:
   food_start: 150
   food_rate: 20
   eo_start: 40
   repop: 5
  food_mass: 0.2
  drag: 0.04
  spike_decay: 0.997
  pond_disaster: 25
  energy_infusion: 75
  auto_track: true
 eo_constants:
  main:
   eo_starting_energy: 10
   rep_variance: 2
   rep_rate: 72
   rep_rate_degree: 2
   rep_t_minimum: 1
   rep_t_maximum: 50
   energy_cap: 400
   healing_drain_min: 0.942
   healing_drain_max: 0.985
   spike_damage: 1.5
   mass_drag: 2
   rest_energy_decay: 0.2
   base_drag_reductor: 20
  body:
   body_mass_factor: 2.5
   recovery: 0.0125
   body_damage: 0.2
   body_decay: 0.95
   max_speed: 2.5
  feeler:
   poke_force_factor: 0.5
   feeler_mass_factor: 1
   length_strength_mass_ratio: 0.6
  dna:
   mutate_time_scale: 1.15
   mutation_factor: 0.13
   mutation_variance: 1.2
   brain_mutate_factor: 0.08
   forget_factor: 0.0125
   initial_variance: 4
   mutation_curve: 3
   color_var_factor: 2
   program_size_limit: 12
   container_size_limit: 10
 log:
  console_level: 2					## 1:debug,2:info,3:warn,4:error,5:fatal
  file_level: 1
  pop_freq: 25
  fr_freq: 25
  types:
   activity: true
   population: true
   framerate: false
override:
 default_overrides:
  
 setting_overrides:
  profile:
   initial_variance: 5
resource:
 font_file: FreeSans.ttf