settings:
 log:
  console_level: 2					## 1:debug,2:info,3:warn,4:error,5:fatal
  file_level: 1
  pop_freq: 25
  types:
   activity: true
   population: true
 environment:
  choice: large
  large:
   w: 640
   h: 480
   food_start: 150
   food_rate: 20
   eo_start: 6
   repop: 5
  small:
   w: 400
   h: 300
   food_start: 50
   food_rate: 45
   eo_start: 4
   repop: 2
  framerate: 10
  food_mass: 0.2
  log_freq: 25
  drag: 0.04
  zones: 4
 eo_constants:
  main:
   rep_threshold: 15
   rep_rate: 2000
   healing_drain: 0.98
  body:
   mass: 10
   recovery: 0.01
   damage: 0.2
  feeler:
   poke_force_factor: 0.5
   mass_factor: 0.1
  dna:
   mutation_factor: 0.12
   mutation_variance: 1.25
   forget_factor: 0.012