choice: regular
settings:
 environment:
  framerate: 10
  framerate_limit: 0.075
  large:
   w: 800
   h: 600
  regular:
   w: 640
   h: 480
  small:
   w: 400
   h: 300
  profile:
   w: 640
   h: 480
 pond:
  large:
   food_start: 234
   food_rate: 35
   eo_start: 16
   repop: 10
  regular:
   food_start: 150
   food_rate: 20
   eo_start: 10
   repop: 5
  small:
   food_start: 50
   food_rate: 45
   eo_start: 4
   repop: 2
  profile:
   food_start: 150
   food_rate: 20
   eo_start: 40
   repop: 5
  food_mass: 0.2
  drag: 0.04
 eo_constants:
  main:
   rep_threshold: 15
   rep_rate: 3300
   energy_cap: 200
   healing_drain: 0.98
  body:
   mass: 10
   recovery: 0.01
   damage: 0.2
  feeler:
   poke_force_factor: 0.5
   mass_factor: 0.1
  dna:
   mutation_factor: 0.13
   mutation_variance: 1.2
   brain_mutate_factor: 0.08
   forget_factor: 0.0125
   initial_variance: 4
   mutation_curve: 3
   color_var_factor: 2
 log:
  console_level: 2					## 1:debug,2:info,3:warn,4:error,5:fatal
  file_level: 1
  pop_freq: 25
  fr_freq: 25
  types:
   activity: true
   population: false
   framerate: true
override:
 profile:
  eo_constants:
   dna:
    initial_variance: 5
resource:
 font_file: FreeSans.ttf